### ISSUE TITLE
Unordered states adding

### ISSUE THREAD

**Issue by sa-lo-mon** [outbrain/Leonardo#106]
Hi,
It seems that there is no option to add unordered states to Leonardo.
I have added two states to Leonardo when the url of the second was more explicit then the url of the first.
When i tried to enable the second state (and obviously disabled the first one) i got error that says that there was no mach to the second url, although there was a mach.

**Comment by dwido** [comment]
Can you provide urls you have used or similar example to reproduce this problem?

**Comment by sagivf** [comment]
Closing until relevant
