### ISSUE TITLE
Fix recorder tab

### ISSUE THREAD

**Issue by sagivf** [outbrain/Leonardo#132]
Broken since removing angular

**Comment by sagivf** [comment]
@tsachis can up have a look at https://github.com/outbrain/Leonardo/blob/master/src/leonardo/ui/views/recorder/state-detail/states-detail.ts#L28

I'm not sure whats going on - we need to figure out when an item in the recorder is an option for an existing state or the user needs to define a new state (with an initial option).

Looking at the old code it seems like `stateActive` is responsible, but doesn't seem to work.

FYI - to test this simple remove/add the `<script src="mock.js"></script>` from examples/angularIL/index.html and look at the login request.

**Comment by MrFrankel** [comment]
fixed
