### ISSUE TITLE
Leonardo is included in production mode

### ISSUE THREAD

**Issue by lavrinec** [outbrain/Leonardo#167]
Hi,
I have been playing with your [Angular example](https://github.com/outbrain/Leonardo/tree/master/examples/ng2-webpack).
Ther is this code in main.ts:
`if (environment.production) {
  enableProdMode();
} else {
  register()
}`

If I set my envirament to production, Leonardo is still included and loaded on the page! The only way I found to disable Leonardo is to comment row register(), but this is not a nice solution.

Regards,
Marko

**Comment by MrFrankel** [comment]
@lavrinec are you using webpack?

**Comment by MrFrankel** [comment]
you should not have the leonardo added to the scripts in production build.
Best is to have a separate angular-cli.json for dev and prod

**Comment by lavrinec** [comment]
So the best way to deal with this would be to have two main.ts and two angular-cli.sjon - one for prod and one for dev. Than I would not need to check environment variable (as it is done in example [here ](https://github.com/outbrain/Leonardo/blob/master/examples/ng2-webpack/src/main.ts)), but I would just include register() in dev main.ts and not in prod.
Did I understand that correctly?

**Comment by vlio20** [comment]
@lavrinec, this is exactly how we do it. We have 2 main.ts files, one for dev and one for prod

**Comment by lavrinec** [comment]
@vlio20 ok, then I will do the same. Thank you for help
