### ISSUE TITLE
Add Edit State option

### ISSUE THREAD

**Issue by alexilyaev** [outbrain/Leonardo#67]
Hey guys, really like the tool :-)

I would like an option to edit a state that I've previously created.
Right now it's only possible if I click on a saved state under RECORDER and update the `Response name` to be exactly the same as the saved state name.

Would have to allow editing a specific option of a state as well.

**Comment by liranviper** [comment]
also, Delete option would be great :)

**Comment by dwido** [comment]
close by https://github.com/outbrain/Leonardo/pull/85
