### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by alexilyaev** [outbrain/Leonardo#68]
On my Mac, if I open the DevTools (docked on the right), the state options dropdowns are off the screen even on 1196px width.

To see it properly I need to scroll to the right.
<img width="1440" alt="screen shot 2015-11-24 at 19 20 17" src="https://cloud.githubusercontent.com/assets/480469/11374771/6ebeb842-92e0-11e5-9a05-ae99fdfc0d2b.png">

**Comment by vlio20** [comment]
resolved in resolved in 6ecbb75c8e6688887db4b184f2597eb44a940208
