### ISSUE TITLE
Make the Leonardo icon draggable

### ISSUE THREAD

**Issue by alexilyaev** [outbrain/Leonardo#71]
Would be useful to drag Leonardo's face to somewhere else on the window :-).

And save it in localStorage as well.

**Comment by vlio20** [comment]
In the next release you will be able to toggle the icon by hitting ctrl + shift + l.

**Comment by vlio20** [comment]
I don't think we should implement the dragging option. Toggling the icon is enough in my opinion. Moreover, we should store in local storage the state (visible/hidden)

**Comment by sagivf** [comment]
Agreed. Close it an implement the localstorage in https://github.com/outbrain/Leonardo/issues/79
