### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by vlio20** [outbrain/Leonardo#74]
For example, when adding a new state we should be stopped if name wasn't set. Same for options.  
In laters stage maybe we should validate the option (response) body.

_ALSO_
add console warning when state is defined without existing (also selected option) #18

**Comment by sagivf** [comment]
add console warning when state is defined without existing (also selected option) #18

**Comment by sagivf** [comment]
- [Don't allow scenarios with the same name ] 
- [Adding a new state we should be stopped if name wasn't set]
- [Adding a new option we should be stopped if name wasn't set]

**Comment by MrFrankel** [comment]
@vlio20 is a traitor so we will ignore him till he goes away...:)
