### ISSUE TITLE
Toggle ui with key combination

### ISSUE THREAD

**Issue by vlio20** [outbrain/Leonardo#78]
Add possibility to show/hide leonardo "dashboard"

**Comment by dwido** [comment]
I think the dashboard should hide when clicking esc

**Comment by vlio20** [comment]
I agree, but esc is widely used and might cause un wanted action on the app which uses leonardo. @dwido, WDYT?

**Comment by sagivf** [comment]
@vlio20 I think you can catch the esc and stop it's propagate it (only when the Leonardo dahsboard is open)

**Comment by vlio20** [comment]
Right, what about the key to open the leonardo UI?

**Comment by sagivf** [comment]
Comman+shift+L perhaps. What ever you see fit I guess

**Comment by vlio20** [comment]
Already taken for toggle the leonardo icon
