### ISSUE TITLE
RESTify Leonardo VIA URL

### ISSUE THREAD

**Issue by yonatanm** [outbrain/Leonardo#8]
encode Leonardo state (enable/disable and the selected scenario) in the URL so you can share a link with specific use case configuration.

What do you say ?

**Comment by sagivf** [comment]
Will start with a simple scenario export/import via url

**Comment by yonatanm** [comment]
cool, keep it rolling

**Comment by sagivf** [comment]
:+1: :8ball: :8ball: :8ball:

**Comment by sagivf** [comment]
Closing untill this becomes a priority
