### ISSUE TITLE
Update in memory state 'save' bug

### ISSUE THREAD

**Issue by justtal** [outbrain/Leonardo#95]
There is a bug when editing state. When sending broadcast to 'leonardo:stateChanged' you don't send the _option.

configuration.srv.js:283

$rootScope.$broadcast('leonardo:stateChanged'); 

should be:

$rootScope.$broadcast('leonardo:stateChanged', _option);

Am I right?

**Comment by sagivf** [comment]
@justtal Sorry for the delayed response and thanks for helping out. We are in the midst of a serious refactor and will be fixing up all the add/edit/remove mechanism. I'll let you know once it's done, and then let us now if the bug still exists.

**Comment by tsachis** [comment]
Actually, it should be:
`$rootScope.$broadcast('leonardo:stateChanged', _state);`
I'll commit a fix soon.
